# ============== DEPLOYMENT VARIABLES ============================
INTERNAL_TLS_ENABLED: false
MONITORING_ENABLED: true
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "info"

TRACING_ENABLED: false
TRACING_HOST: 'nc-diagnostic-agent'
TRACING_SAMPLER_RATELIMITING: 10

DISABLE_DEPRECATED_API: false

DBAAS_AGENT_NAMESPACE_ISOLATION_ENABLED: true
DBAAS_DEFAULT_SEC_POLICY: "allow"
K8S_SERVICE_TYPE: 'CLUSTER_IP'
CONSUL_ENABLED: false
CONSUL_URL: ''